# Generated by Django 5.2.4 on 2025-07-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coin',
            index=models.Index(fields=['name', 'contract_address', 'instructions'], name='coin_coin_name_5321cc_idx'),
        ),
    ]
